### ISSUE TITLE
ペット効果が発動時にエラーが発生する

### ISSUE THREAD

**Issue by usachoco** [roratorio-hub/ratorio#73]
Googleフォームからお寄せ頂いたバグ報告です

確認済み
・避難所の計算機では発生しない
・エドガに限らずフリオニでも発生する
・キャットナインテイルでは発生しない
・セーブ/ロードを介さなくても発生する（インクを選んでワンダーエッグ装備→親密度最高のエドガを装備→カードを装備）

```
1月13日の更新後から何らかの条件で攻撃方法の選択ができないという症状が出るようになりました。
色々試したのですが何がトリガーになるのか原因は掴めませんでしたが、一度この状態になると何をしても問題は改善しませんでした。
セーブ時におかしくなるのかと思ったのですが、セーブしなくても同じ状態になることがありました。
またこの状態でセーブすると同じデータでは二度と攻撃方法を選択できなくなります。

具体的なエラーは次の通りです。

Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at CAttackMethodAreaComponentManager.GetEffectiveAttackMethodDataArray (CAttackMethodAreaComponentManager.js:1538:33)
    at CAttackMethodAreaComponentManager.RebuildAttackMethodSelect (CAttackMethodAreaComponentManager.js:684:94)
    at CAttackMethodAreaComponentManager.RebuildControls (CAttackMethodAreaComponentManager.js:494:36)
    at #applyDataToControlsAttackConf (CSaveDataManager.js:1709:37)
    at funcCallApplyAttackConf (CSaveDataManager.js:608:40)
    at CSaveDataManager.applyDataToControls (CSaveDataManager.js:754:3)
    at CSaveController.loadFromURL (CSaveController.js:354:22)
    at CSaveController.loadCharaData (CSaveController.js:271:19)
    at OnClickLoadSaveData (saveload.js:35:36)
    at HTMLButtonElement.onclick (calcx.html:292:117)

CAttackMethodAreaComponentManager.js:1538:33は以下でした。

// 使用可能フラグが立っていない場合は、処理しない
if (InsertSkill[usableSkillId][USABLE_SKILL_DATA_INDEX_ATTACKABLE] != 1) {
        continue;
}

エラーとなるセーブデータサンプルを以下に提示致します。
https://roratorio-hub.github.io/ratorio/ro4/m/calcx.html?cx1cy1AqWpu8bOqueOO.5M1cz11002GjFw1bn4BQuX0cz12002GjcF1CytoWoW2cz13002GjoBl_m4pzuJ3cz14002GhUlsJCmPodfcz15002Ehql9rPiN5cz16002GjeAGyyirviT3cz17002yjRwmyA1vd2cz18002GjAJ6Fzinhg61cz19002GhG9usk4DvP8cz1a002GhLuoLBz3iEecz1b.4hM1cz1c.4hOacz1d00M0jPgw103cz1e00M0jPhkf22cz1f00c0jOvsn03cz1g00M0jPiw933cz1h00M0jPjwc03cz1i00M0jPkwc03cA1Z_1127456b89a3cA128c0cA1vgfdejgh2cB1.o69.8EqlcC1.a800hd6cD1.e2hCfaaafa55aa5cE1.hzGcK1.ag08a1cR100pEMncW10041

ご確認ください。
```

```
その他の支援/設定 (暫定追加機能)でキューペットのエドガを選択しても
サイズによる武器ダメージのペナルティが発生しないが発動しないようです。
×はついていないのですが実は未実装・・・なんですかね？
```

```
先程攻撃方法が選択できないと報告した者ですが、原因がわかりました。
ペットにエドガを選択した状態で何らかの装備、カード、エンチャントなどを変更すると選択できなくなるようです。
ペットをエドガ以外に変更し、もう一度装備、カード、エンチャントなどを変更することで再び選択可能となるようです。
```

**Comment by usachoco** [comment]
以下のエラーメッセージに加えて
エドガやフリオニのようなスキル使用可能になるMVPペットで発生するのに
キャットナインテイルのようなスキル使用可能にならないペットで発生しないことから
使用可能スキルの処理に問題があるかもしれません

![image](https://github.com/roratorio-hub/ratorio/assets/149866018/ea653779-f54c-474b-8358-6b8041119ef3)

**Comment by usachoco** [comment]
お寄せ頂いた情報の通り 1/12 時点のコードではこの事象は再現されませんでした
facea68130e33c7c60172ac23223ec2dcb695c91

**Comment by usachoco** [comment]
#76 で修正済みです

**Comment by usachoco** [comment]
クローズ済みですが関連する情報を頂いていたので追記します

```
『その他の支援/設定(暫定追加機能)』のペット設定で異常な値が出るので報告します。

ペット単独効果で、追加ダメージ (種族up系,敵属性up系,属性up系など)がある場合、
拡張機能表示において、「2000000000000414％」などの表示が出て、ダメージが1ダメになっております。

対象のペットは
・エンジェリング
・ダークロード
・ドケビ
・ドモヴォイ
・ペクソジン
・マスターリング
・ハイオーク
・ジルタス
・グラウンドデリーター
・キャットナインテイル
・エリザ
・エリオット
・インプ
・イシス

確認お願いします。
```
